version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${DOCKER_PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks: 
      - auth_be

  db:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "${DATABASE_PORT}:${DATABASE_DOCKER_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks: 
      - auth_be

volumes:
  mongodb_data:

networks:
  auth_be: {}
